### ISSUE TITLE
Quick question for clarification on usage.

### ISSUE THREAD

**Issue by donmstewart** [marrow16/valix#37]
Quick question for clarification on usage. 

I have added `v8n` tags to my go structs alongside existing `json` tags. 

When I run the validator on the JSON output as a `map[string]interface{}` I get violations for all the attributes I have added tags for i.e. all the attributes on the struct. The code in the violations is `42209`. The `Path` is empty & `BadRequest` is `false`.

Thanks for creating valix it looks like it is going to be super useful.

Many thanks.

_Originally posted by @donmstewart in https://github.com/marrow16/valix/discussions/36_

**Comment by marrow16** [comment]
Hi @donmstewart 

42209 is the code for 'Unknown property' (the violations should be giving the name of the properties that were unknown).

Perhaps your JSON `map[string]interface{}` being validated has properties that were not defined in your structs?

If you want to ignore unknown properties, set the `IgnoreUnknownProperties` to true on your validator... e.g.

```
package main

import (
    "fmt"
    "github.com/marrow16/valix"
)

type myStruct struct {
    Foo string `json:"foo,omitempty" v8n:"notNull,mandatory,&StringNotEmpty{}"`
    Bar string `json:"bar" v8n:"notNull,mandatory,&StringNotEmpty{}"`
}

func main() {
    v := valix.MustCompileValidatorFor(myStruct{}, &valix.ValidatorForOptions{
        IgnoreUnknownProperties: true,
    })

    req := map[string]interface{}{
        "foo":   "ok",
        "bar":   "ok",
        "dunno": "this property is unknown!",
    }

    ok, violations := v.Validate(req)
    fmt.Printf("First validated ok?: %v\n", ok)
    for i, violation := range violations {
        fmt.Printf("Violation[%d] - Message='%s', Property='%s', Path='%s'\n", i, violation.Message, violation.Property, violation.Path)
    }

    // don't ignore unknown properties...
    v.IgnoreUnknownProperties = false

    ok, violations = v.Validate(req)
    fmt.Printf("Second validated ok?: %v\n", ok)
    for i, violation := range violations {
        fmt.Printf("Violation[%d] - Message='%s', Property='%s', Path='%s'\n", i, violation.Message, violation.Property, violation.Path)
    }
}
```

> Thanks for creating valix it looks like it is going to be super useful.

Thank you

hth
Marrow
